# Generated by Django 6.0.6 on 2026-06-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='import_row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
