# Generated by Django 6.0.6 on 2026-06-14 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='groups.group')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_sessions',
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('anomaly_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('original_value', models.TextField(blank=True)),
                ('resolved_value', models.TextField(blank=True)),
                ('action_taken', models.CharField(choices=[('auto_fixed', 'Auto Fixed'), ('skipped', 'Skipped'), ('needs_review', 'Needs Review'), ('reclassified', 'Reclassified')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='importer.importsession')),
            ],
            options={
                'db_table': 'import_anomalies',
            },
        ),
    ]
